# Generated by Django 6.0.6 on 2026-06-29 19:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('data_sources', '0002_datasource_processing_error_and_more'),
        ('portfolio_projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectVisualization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('visualization_type', models.CharField(choices=[('bar_chart', 'Bar chart'), ('line_chart', 'Line chart'), ('scatter_plot', 'Scatter plot'), ('pie_chart', 'Pie chart'), ('data_table', 'Data table'), ('kpi_card', 'KPI card')], max_length=30)),
                ('x_axis_column', models.CharField(blank=True, max_length=120)),
                ('y_axis_column', models.CharField(blank=True, max_length=120)),
                ('aggregation_method', models.CharField(choices=[('none', 'None'), ('sum', 'Sum'), ('average', 'Average'), ('count', 'Count'), ('minimum', 'Minimum'), ('maximum', 'Maximum')], default='none', max_length=20)),
                ('visualization_config', models.JSONField(blank=True, default=dict)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('portfolio_project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_visualizations', to='portfolio_projects.portfolioproject')),
                ('source_dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_visualizations', to='data_sources.datasource')),
            ],
            options={
                'ordering': ['portfolio_project', 'display_order', 'id'],
            },
        ),
    ]
