# Generated by Django 6.0.6 on 2026-07-16 04:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_sources', '0003_datasource_source_url_alter_datasource_file_and_more'),
        ('data_visualizations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectvisualization',
            name='embed_url',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='projectvisualization',
            name='source_dataset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project_visualizations', to='data_sources.datasource'),
        ),
        migrations.AlterField(
            model_name='projectvisualization',
            name='visualization_type',
            field=models.CharField(choices=[('bar_chart', 'Bar chart'), ('line_chart', 'Line chart'), ('scatter_plot', 'Scatter plot'), ('pie_chart', 'Pie chart'), ('data_table', 'Data table'), ('kpi_card', 'KPI card'), ('external_embed', 'External embed')], max_length=30),
        ),
    ]
