# Generated by Django 6.0.6 on 2026-07-16 03:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_publicprofile_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publicprofile',
            name='avatar',
        ),
    ]
