# Generated by Django 6.0.6 on 2026-06-29 03:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('portfolio_projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('source_type', models.CharField(choices=[('csv', 'CSV'), ('excel', 'Excel')], max_length=20)),
                ('file', models.FileField(upload_to='data_sources/')),
                ('original_filename', models.CharField(blank=True, max_length=255)),
                ('columns_schema', models.JSONField(blank=True, default=dict)),
                ('row_count', models.PositiveIntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_sources', to='portfolio_projects.portfolioproject')),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
