# Generated by Django 6.0.6 on 2026-06-29 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_sources', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='datasource',
            name='processing_error',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='datasource',
            name='processing_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processed', 'Processed'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
    ]
