# Generated by Django 6.0.6 on 2026-07-14 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_sources', '0002_datasource_processing_error_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='datasource',
            name='source_url',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='datasource',
            name='file',
            field=models.FileField(blank=True, upload_to='data_sources/'),
        ),
        migrations.AlterField(
            model_name='datasource',
            name='source_type',
            field=models.CharField(choices=[('csv', 'CSV'), ('excel', 'Excel'), ('google_sheets', 'Google Sheets')], max_length=20),
        ),
    ]
